spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    hikari:
      password: ${DB_PASSWORD:postgres}
      username: ${DB_USERNAME:postgres}
      maximum-pool-size: 20
      minimum-idle: 5